# Generated by Django 3.1.1 on 2020-09-03 00:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DataNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('type', models.CharField(choices=[('READER', 'Reader'), ('CALCULATOR', 'Calculator'), ('AGGREGATOR', 'Aggregator'), ('WRITER', 'Writer')], db_index=True, max_length=20)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graph.unit')),
            ],
            options={
                'verbose_name': 'Data Node',
                'verbose_name_plural': 'Data Nodes',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='DataEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_nodes', to='graph.datanode')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_nodes', to='graph.datanode')),
            ],
            options={
                'verbose_name': 'Data Edge',
                'verbose_name_plural': 'Data Edges',
                'unique_together': {('source', 'dest')},
            },
        ),
    ]
