# Generated by Django 3.1.1 on 2020-09-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanode',
            name='params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
