# Generated by Django 3.1.1 on 2020-10-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20200903_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='datanode',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
